
name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
- master

jobs:
  - template: angular.build.yml
  - job: GenerateReleaseNotes
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'exampleApp'
        publishLocation: 'Container'
