
name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
  branches:
    include:
      - master

variables:
  workingDir: 'HR.GEM.Frontend'
  projectName: 'hr-gem-frontend'

jobs:
#  - template: angular.build.yml
  - job: GenerateReleaseNotes
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'exampleApp'
        publishLocation: 'Container'
